language: ruby
rvm:
- 2.5.1

before_script:
 - chmod +x ./scripts/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
