title: deadbaed
author: Philippe Loctaux
description: broke my bed, it's now dead
github_username: x4m3
twitter_username: philippeloctaux

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Europe/Paris
permalink: /:year/:month/:title/

# Plugins
plugins:
  - jekyll-remote-theme

# Theme settings
remote_theme: heiswayi/the-plain

# Server settings
port: 8002

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - readme.md
  - scripts/
  - _posts/template.md
