title: deadbaed
description: broke my bed, it's now dead
baseurl: "" 
url: "https://db.philippeloctaux.com" 
github_username:  ploctaux
github_repo: deadbaed
social_link: twitter
social_username: philippeloctaux

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: gray
encoding: utf-8
timezone: Europe/Paris
permalink: /:year/:month/:title
exclude: [readme.md, Gemfile, Gemfile.lock]
plugins:
  - jekyll-feed

# Server settings
port: 8002

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
